

spring:
  datasource:
    url: jdbc:h2:mem:assets
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
server:
  port: 8080

app:
  message:
    welcome: "Let's manage our assets efficiently!"
